### ISSUE TITLE
svd-parser depency fail

### ISSUE THREAD

**Issue by gediz** [MabezDev/idf2svd#15]
Hello. Thank you for this valuable tool. I have encountered a depency problem.

>  cargo run 
>     Updating crates.io index
>     Updating git repository `https://github.com/rust-embedded/svd.git`
> error: failed to load source for a dependency on `svd-parser`
> 
> Caused by:
>   Unable to update https://github.com/rust-embedded/svd.git?branch=build#f8c26aa4
> 
> Caused by:
>   revspec 'f8c26aa421a19b5fde91f7cde969b9985a246fca' not found; class=Reference (4); code=NotFound (-3)

I removed commit hash part from [this](https://github.com/MabezDev/idf2svd/blob/master/Cargo.lock#L80) line for a temporary fix and this made me able to execute `cargo run` without any other depency problem. But i do not know if it would cause any other problem.

**Comment by jessebraham** [comment]
Thanks for opening this issue! I believe I have fixed this in #16. There is more information regarding the cause of this problem in the PR.
