### ISSUE TITLE
Updated ESP8266 Technical Reference is missing appendices

### ISSUE THREAD

**Issue by jessebraham** [MabezDev/idf2svd#18]
In version 1.5 of the ESP8266 Technical Reference, uploaded on 2020/07/17, all four chapters of the Appendix are missing. This means `tabula.jar` fails to parse the tables within those chapters (because they don't exist) and we cannot build the SVD.

I have sent an email to Espressif to let them know. In the meantime version 1.4 is still available at [archive.org](https://web.archive.org/web/*/https://www.espressif.com/sites/default/files/documentation/esp8266-technical_reference_en.pdf).

**Comment by icewind1991** [comment]
1.6 has been released and contains the needed parts.

That said, it might be worth to just checking the appendices into the repo

**Comment by jessebraham** [comment]
Great, thanks for the update! And yeah, I'm generally against putting PDFs in repos but in this case I think it might make sense.
