### ISSUE TITLE
Indexed peripherals

### ISSUE THREAD

**Issue by MabezDev** [MabezDev/idf2svd#2]
Some peripherals in the idf are indexed, i.e there are two identical I2C peripherals on the esp32, instead of creating register definitions for both, they are defined once with offset.

This generator doesn't properly handle this at the moment, and only creates one peripheral.

**Comment by MabezDev** [comment]
The current approach simply inserts a generic blank peripheral at the start, see https://github.com/MabezDev/idf2svd/blob/c433ffab105c607bd4f868765c9f2967eba09a0a/src/lib.rs#L161 . This will require some post processing of the svd to copy and give them the correct base address

**Comment by sepotvin** [comment]
Hi, The I2S peripheral is also indexed and should probably be added to the list. The latest esp32 PAC only shows I2S0 as I2S.

**Comment by MabezDev** [comment]
Hi @sepotvin, I forgot about this repo. There are now official SVD's in the https://github.com/espressif/svd repo. Please file the issues there.
